global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'besu'
    static_configs:
      - targets: ['besu:8545']

  - job_name: 'chainlink'
    static_configs:
      - targets: ['chainlink:6688']

  - job_name: 'blockscout'
    static_configs:
      - targets: ['blockscout:4000']

  - job_name: 'graph-node'
    static_configs:
      - targets: ['graph-node:8020']

  - job_name: 'remix'
    static_configs:
      - targets: ['remix:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
